---
title: "Our Respondents' Thoughts about InnerSource Commons"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
  font-size: 150%;
}
</style>

```{r setup, prep, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(maps)
library(hrbrthemes)
library(viridis)
library(scales)
library(stringr)
library(ggthemr)
library(RColorBrewer)
library(egg)
library(dplyr)
require(scales)
library(likert)
library(plyr)
library(stargazer)

myPalette <- brewer.pal(5, "Set2") 
ggthemr("lilac") 

# For processing multiple answer data
process.mad = function(x){
  x = x[!(is.na(x))]
  x = unlist(x)
  x = paste(x,',')
  x = unlist(strsplit(x,','))
  x = trimws(x)
  x = x[x != ""]

  return(table(x))
}
process.lik = function(x){
  return(factor(x, levels = c("Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree")))
}
process.lik.imp = function(x){
  return(factor(x, levels = c("Not Important", "Slightly Important", "Medium Important", "Very Important", "Critically Important")))
}
sub.lik = function(x){
  return(trimws(gsub("\\."," ",gsub('.*\\.\\.\\.','',x))))
}




sudata = read.csv("_DONOTADD_State_of_the_InnerSource_Survey 2020_Responses.csv", na.strings = c('NA',''))
sudata$Timestamp = NULL
header.map = colnames(sudata)
names(header.map) = paste0("v",seq(79))
colnames(sudata) = paste0("v",seq(79))
sudata$v79 = NULL
sudata$v78 = NULL
sudata = data.frame(lapply(sudata, trimws))
# Shorten some Responses
sudata$v6 = gsub("Recognition that the current approach won't scale with our ambitions / trajectory.", 'Accommodate Scaling', sudata$v6)
sudata$v6 = gsub("Maintain and develop software developed by contractors that are no longer with the organization", 'Maintain Software w/o Contractor Support', sudata$v6)
sudata$v6 = gsub("Avoid wasted time/resources solving similar problems multiple times in isolation", 'Creating reusable software', sudata$v6)
sudata$v8 = gsub("We formed a cross organization group under our Open Source Program Office to foster the practice of InnerSource",'Establish InnerSource Foundation', sudata$v8)

# Specific Answer questions
toFact = c(2,4,11:15,18:40, 43:61, 70:72)
sudata[,toFact] = lapply(sudata[,toFact], as.factor)
# Numeric data
numdata = c(1,3,5,10,63,67,68,73,75,76)
for (i in numdata){
  sudata[,i] = as.numeric(gsub('[^0-9.-]','',sudata[,i]))
}
```

# **Overall Usefulness of InnerSource Commons**

```{r, progress-success, echo=FALSE, fig.show="hold", out.width="90%", warning=FALSE, fig.width=12, fig.height=2}
# Useful
sudata$v63 = factor(sudata$v63, levels = c(1,2,3,4,5))
levels(sudata$v63) = c("Not at all Useful",'Not so Useful','Somewhat Useful',"Very Useful","Extremely Useful")
lv = sudata[,63,drop=F]
colnames(lv) = c('Usefulness')
lk = likert(lv)
plot(lk, centered=T, plot.percents =T, text.size=5, wrap=30, plot.percent.neutral=F, plot.percent.low=T, plot.percent.high=T) + theme(text = element_text(size=18)) + guides(fill=guide_legend(paste0("(N=",length(na.omit(sudata$v63)),')')))

```
<br></br>

# **Most Appealing Features of InnerSource Commons**
```{r, feature, echo=FALSE, fig.show="hold", out.width="70%", warning=FALSE}
# Big Ones
t=process.mad(sudata$v64)
df = as.data.frame(t)
df$x = as.character(levels(df$x))
df$newx = str_wrap(df$x, width = 20)
df = df[order(df$Freq, decreasing = T),]
df$piepercent<- round(100*df$Freq/length(na.omit(sudata$v42)), 0)
ggplot(data=df, aes(x = reorder(newx, Freq), y = Freq)) +
  geom_bar(position="dodge",stat="identity") + coord_flip() + 
  labs(title=str_wrap("", 20), x='', y = paste0('No. of Respondents (N=',length(na.omit(sudata$v64)),')')) +  scale_x_discrete(guide = guide_axis(n.dodge=2)) +theme(text = element_text(size=16)) +  geom_text(aes(label=paste0(Freq,'(',piepercent,"%)")), position=position_dodge(width=0.9), hjust = -0) + scale_y_continuous(limits = c(0,32))

```
<br></br>

# **What People LIKE about InnerSource Commons:**
```{r, echo=FALSE, results="asis"}
# Like
cat(str_to_sentence(paste("* ",na.omit(sudata$v65), collapse = "\n")))

```
<br></br>

# **How to make InnerSource Commons more Useful?**

```{r, echo=FALSE, results="asis"}
cat(str_to_sentence(paste("* ",na.omit(sudata$v66), collapse = "\n")))

```
