---
title: "**Respondent profile**"
output: html_document
---
<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
  font-size: 150%;

}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(maps)
library(hrbrthemes)
library(viridis)
library(scales)
library(stringr)
library(ggthemr)
library(RColorBrewer)
library(egg)
library(dplyr)
library(likert)
library(plyr)

myPalette <- brewer.pal(5, "Set2") 
ggthemr("grape") 

# For processing multiple answer data
process.mad = function(x){
  x = x[!(is.na(x))]
  x = unlist(x)
  x = paste(x,',')
  x = unlist(strsplit(x,','))
  x = trimws(x)
  x = x[x != ""]

  return(table(x))
}
process.lik = function(x){
  return(factor(x, levels = c("Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree")))
}
sub.lik = function(x){
  return(trimws(gsub("\\."," ",gsub('.*\\.\\.\\.','',x))))
}

sudata = read.csv("_DONOTADD_State_of_the_InnerSource_Survey 2020_Responses.csv")
sudata$Timestamp = NULL
header.map = colnames(sudata)
names(header.map) = paste0("v",seq(79))
colnames(sudata) = paste0("v",seq(79))
sudata$v79 = NULL
sudata$v78 = NULL
sudata = data.frame(lapply(sudata, trimws))
# Shorten some Responses
sudata$v4 = gsub('Top-Down: Someone from management initiated the adoption', 'Top-Down', sudata$v4)
sudata$v4 = gsub('A mix of both', 'Mixed', sudata$v4)
sudata$v4 = gsub('Bottom-Up: One/A small group of developers started the initiative', 'Bottom-Up', sudata$v4)
sudata$v6 = gsub("Recognition that the current approach won't scale with our ambitions / trajectory.", 'Scaling', sudata$v6)
sudata$v6 = gsub("Maintain and develop software developed by contractors that are no longer with the organization", 'Maintain Software w/o Support', sudata$v6)
sudata$v6 = gsub("Avoid wasted time/resources solving similar problems multiple times in isolation", 'Creating reusable software', sudata$v6)
sudata$v8 = gsub("We formed a cross organization group under our Open Source Program Office to foster the practice of InnerSource",'Establish InnerSource Foundation', sudata$v8)

# Specific Answer questions
toFact = c(2,4,11:15,18:40, 43:61, 70:72)
sudata[,toFact] = lapply(sudata[,toFact], as.factor)
# Numeric data
numdata = c(1,3,5,10,63,67,68,73,75,76)
for (i in numdata){
  sudata[,i] = as.numeric(gsub('[^0-9.-]','',sudata[,i]))
}

#country data
t=process.mad(sudata$v69)
df0 = as.data.frame(t)
df0$x = as.character(levels(df0$x))

df2 = data.frame('region'=df0$x)
df2$lat = c(2,-15,15, 32, 50, 29, 46, -24)
df2$long = c(24, -55, 80, 118 ,7, 47, -93, 137)
```

# Where our Survey Respondents are from
```{r, echo=FALSE, out.width="80%", fig.align="center"}
#country data
t=process.mad(sudata$v71)
df0 = as.data.frame(t)
df0$x = as.character(levels(df0$x))

df = merge(df2, df0, by.x = 'region', by.y = 'x')

worlddata = map_data('world')
ggplot() +
  geom_polygon(data=worlddata, aes(x = long, y = lat, group = group), fill="#e0e0e0", colour = "white", alpha=0.7)  +  geom_path(data = worlddata, aes(x = long, y = lat, group = group), alpha=0.7) + geom_point(data = df, aes(x = long, y = lat, size = Freq), fill='#bf24ee', alpha= 0.7, shape=21, color="black") + scale_size(range = c(15,40))+ geom_text(data=df, aes(x = long, y = lat, label=Freq),position = position_dodge(width=0.9),  size=10) + scale_fill_viridis(discrete=TRUE, guide=FALSE, option="A") + theme_void() + theme(legend.position="none") 

```
<br></br>

# **Age and Gender Profiles**
<br>
```{r, echo=FALSE, figures-side, fig.show="hold", out.width="50%", results='hide', fig.retina=1, warning=FALSE,message=FALSE,error=FALSE}
#Gender
tf = as.data.frame(table(sudata$v72))
tf$piepercent<- round(100*tf$Freq/sum(tf$Freq), 1)
pie(tf$Freq, labels = paste0(tf$piepercent,"%"), main = paste0("Gender distribution of \n the Survey Respondents(N=",length(na.omit(sudata$v72)),')') ,col=myPalette, cex.lab=2, cex.axis=2, cex.main=2, cex.sub=2)
legend("bottomright",tf$Var1, cex = 1.2, fill = myPalette, legend = tf$Var1)
#Age
plt1 <- subset(sudata, !is.na(v73)) %>% select(v73) %>%
  ggplot(aes(x="", y = v73)) +
  geom_boxplot(fill = "lightblue", color = "black") + 
  coord_flip() +
  xlab("") + ylab("Age Distribution") +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), text = element_text(size=20))
plt2 <- ggplot(data = subset(sudata, !is.na(v73)), aes(x=v73, fill = v72)) +
  geom_histogram( binwidth = 1, color='black', alpha=0.5, position = "identity")  +
  labs(title = paste0(' Age distribution of the \n Survey Respondents(N=',length(na.omit(sudata$v73)),')'), x='Age', y='No. of Respondents', fill="Gender" ) + theme(text = element_text(size=20)) 
invisible(egg::ggarrange(plt2, plt1, heights = 2:1)) 

```
<br></br>

# **Professional Roles and Experience **

```{r, echo=FALSE, fig.show="hold", out.width="50%", results='hide', fig.retina=1, warning=FALSE,message=FALSE,error=FALSE, fig.height=7}

# Role
t=process.mad(sudata$v74)
df = as.data.frame(t)
df$x = as.character(levels(df$x))
df$newx = str_wrap(df$x, width = 20)
df = df[order(df$Freq, decreasing = T),]
df$piepercent<- round(100*df$Freq/length(na.omit(sudata$v74)), 0)

ggplot(data=df, aes(x = reorder(newx, Freq), y = Freq)) +
  geom_bar(position="dodge",stat="identity") + coord_flip() + 
  labs(title=str_wrap(paste0("Professional Role of Respondents (N=",length(na.omit(sudata$v74)),")"), 30), x='', y = 'No. of Respondents') +  scale_x_discrete(guide = guide_axis(n.dodge=2)) +theme(text = element_text(size=16)) +  geom_text(aes(label=paste0(Freq,'(',piepercent,"%)")), position=position_dodge(width=0.9), hjust = -0) + scale_y_continuous(limits = c(0,14))

# Experience
plt1 <- subset(sudata, !is.na(v75)) %>% select(v75) %>%
  ggplot(aes(x="", y = v75)) +
  geom_boxplot(fill = "lightblue", color = "black") + 
  coord_flip() +
  xlab("") + ylab("Years of Experience Distribution") +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), text = element_text(size=20))
plt2 = ggplot(data = subset(sudata, !is.na(v75)), aes(x=v75, fill = v72)) +
  geom_histogram( binwidth = 1, color='black', alpha=0.5, position = "identity")  +
  labs(title = paste0(' Years of Experience distribution of the \n Survey Respondents(N=',length(na.omit(sudata$v75)),')'), x='Experience in Years', y='No. of Respondents' , fill="Gender") + theme(text = element_text(size=20)) 
invisible(egg::ggarrange(plt2, plt1, heights = 2:1)) 

```
<br></br>




